name: Release

on:
  push:
    tags:
      - "v*"
  workflow_run: {}

jobs:
  build:
    continue-on-error: true

    strategy:
      matrix:
        include:
          - release_for: Linux-GNU-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: amd64
            args: "--locked --release"
            bin: cardaminal

          - release_for: Linux-GNU-armv7
            os: ubuntu-latest
            target: "armv7-unknown-linux-gnueabihf"
            arch: arm64
            args: "--locked --release"
            bin: cardaminal

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: amd64
            args: "--locked --release"
            bin: cardaminal.exe

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            arch: amd64
            args: "--locked --release"
            bin: cardaminal

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: both
          target: ${{ matrix.target }}
          args: ${{ matrix.args }}
          strip: true

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cardaminal-${{ matrix.release_for }}
          path: target/${{ matrix.target }}/release/${{ matrix.bin }}
